// src/store/actions/messageActionTypes.js

const messageActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USERS: 'SET_USERS',
  SET_INDIVIDUAL_MESSAGES: 'SET_INDIVIDUAL_MESSAGES',
  SET_GROUP_MESSAGES: 'SET_GROUP_MESSAGES',
  SELECT_ROOM: 'SELECT_ROOM',
  UPDATE_MESSAGES: 'UPDATE_MESSAGES',
  RESET_TYPING_INDICATOR: 'RESET_TYPING_INDICATOR',
  CLEAR_UNREAD_COUNT: 'CLEAR_UNREAD_COUNT',
  UPDATE_LAST_MESSAGE: 'UPDATE_LAST_MESSAGE',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_TYPING_INDICATOR: 'SET_TYPING_INDICATOR',
};

export default messageActionTypes;
